#******************************************************************************
# Deploys a stateful Postgres 13 instance with service.
#******************************************************************************
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/version: '13'
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: database
    spec:
      template:
        metadata:
          name: postgres
          labels:
            app.kubernetes.io/name: postgres
            app.kubernetes.io/version: '13'
            app.kubernetes.io/part-of: ocp-demo
            app.kubernetes.io/component: database
        spec:
          containers:
            - name: postgres
              image: postgres:13
              imagePullPolicy: Always
              ports:
                - containerPort: 5432
              envFrom:
                - secretRef:
                    name: postgres-config
              env:
                - name: PGDATA
                  value: "/var/lib/postgresql/data/pgdata"
                - name: POSTGRES_DB
                  value: "ocp-demo"
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: postgres-db
          volumes:
            - name: postgres-db
              persistentVolumeClaim:
                claimName: postgres-db
      selector:
        matchLabels:
          app.kubernetes.io/name: postgres
          app.kubernetes.io/part-of: ocp-demo
          app.kubernetes.io/component: database
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgres-db
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: database
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: database
    spec:
      type: ClusterIP
      ports:
        - port: 5432
      selector:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: database
  - apiVersion: v1
    kind: Secret
    metadata:
      name: postgres-config
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: database
      annotations:
        avp_path: "secret/data/vplugin/supersecret"
    stringData:
      POSTGRES_USER: <postgres_username>
      POSTGRES_PASSWORD: <postgres_password>

