#******************************************************************************
# Deploys the OpenShift Demo Backend service.
#******************************************************************************
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ocp-demo-backend
      labels:
        app.kubernetes.io/name: ocp-demo-backend
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: backend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: ocp-demo-backend
          app.kubernetes.io/version: 1.0.0-SNAPSHOT
      template:
        metadata:
          labels:
            app.kubernetes.io/name: ocp-demo-backend
            app.kubernetes.io/version: 1.0.0-SNAPSHOT
            app.kubernetes.io/part-of: ocp-demo
            app.kubernetes.io/component: backend
        spec:
          containers:
            - image: "nexus.cs.axians.nl/ocp-demo/backend:1.0.0-SNAPSHOT"
              imagePullPolicy: "Always"
              name: "ocp-demo-backend"
              envFrom:
                - configMapRef:
                    name: ocp-demo-backend-config
              ports:
                - containerPort: 8080
                  name: "http"
                  protocol: "TCP"
  - apiVersion: v1
    kind: Service
    metadata:
      name: ocp-demo-backend
      labels:
        app.kubernetes.io/name: ocp-demo-backend
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: backend
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: ocp-demo-backend
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      ports:
        - port: 8080
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ocp-demo-backend-config
      labels:
        app.kubernetes.io/name: ocp-demo-backend
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: backend
      annotations:
        avp_path: "secret/data/vplugin/supersecret"
    stringData:
      QUARKUS_DATASOURCE_USER: <postgres_username>
      QUARKUS_DATASOURCE_PASSWORD: <postgres_password>
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgres://postgres:5432/ocp-demo'