#******************************************************************************
# Deploys the OpenShift Demo Backend service.
#******************************************************************************
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ocp-demo-ui
      labels:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: frontend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: ocp-demo-ui
          app.kubernetes.io/version: 1.0.0-SNAPSHOT
      template:
        metadata:
          labels:
            app.kubernetes.io/name: ocp-demo-ui
            app.kubernetes.io/version: 1.0.0-SNAPSHOT
            app.kubernetes.io/part-of: ocp-demo
            app.kubernetes.io/component: frontend
        spec:
          containers:
            - image: "nexus.cs.axians.nl/ocp-demo/ui"
              imagePullPolicy: "Always"
              name: "ocp-demo-ui"
              ports:
                - containerPort: 8080
                  name: "http"
                  protocol: "TCP"
  - apiVersion: v1
    kind: Service
    metadata:
      name: ocp-demo-ui
      labels:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: frontend
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      ports:
        - port: 8080
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ocp-demo-ui
      labels:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: forntend
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ocp-demo-ui