#******************************************************************************
# Deploys the OpenShift Demo Backend service.
#******************************************************************************
apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: ocp-demo-ui
      labels:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: frontend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: ocp-demo-ui
          app.kubernetes.io/version: 1.0.0-SNAPSHOT
      template:
        metadata:
          labels:
            app.kubernetes.io/name: ocp-demo-ui
            app.kubernetes.io/version: 1.0.0-SNAPSHOT
            app.kubernetes.io/part-of: ocp-demo
            app.kubernetes.io/component: frontend
        spec:
          containers:
            - image: "nexus.cs.axians.nl/ocp-demo/ui:0.20"
              imagePullPolicy: "Always"
              name: "ocp-demo-ui"
              ports:
                - containerPort: 3000
                  name: "http"
                  protocol: "TCP"
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                initialDelaySeconds: 30
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 3
              livenessProbe:
                tcpSocket:
                  port: 3000
                initialDelaySeconds: 45
                periodSeconds: 20
      strategy:
        canary:
          steps:
            - setWeight: 50
  - apiVersion: v1
    kind: Service
    metadata:
      name: ocp-demo-ui
      labels:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: frontend
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      ports:
        - port: 3000
          targetPort: 3000
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ocp-demo-ui
      labels:
        app.kubernetes.io/name: ocp-demo-ui
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: ocp-demo
        app.kubernetes.io/component: frontend
    spec:
      port:
        targetPort: 3000
      to:
        kind: Service
        name: ocp-demo-ui